name: Signals
favicon: null
layout_spectrum: 0.1667203065007925
typography_spectrum: 0.6885968339629471
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.26371417776681483
  lightness: 0.3667261698283255
  saturation: 0.1698203356936574
  rhythmicContrast: 0.13294924702495337
purpose: []
